working on front end
iporollo/cerebralvalley-events pull request #3
Opened 2024-04-12 20:15 UTC by nj606214

2024-04-12 22:26 UTC, raydelvecchio commented on components/EventsColumn.tsx
> +    });
Receiving the following error when I make the API call by submitting a query and pressing the button on the frontend:

`SyntaxError: Unexpected token < in JSON at position 0
    at JSON.parse (<anonymous>)
    at parseJSONFromBytes (node:internal/deps/undici/undici:6662:19)
    at successSteps (node:internal/deps/undici/undici:6636:27)
    at node:internal/deps/undici/undici:1236:60
    at node:internal/process/task_queues:140:7
    at AsyncResource.runInAsyncScope (node:async_hooks:203:9)
    at AsyncResource.runMicrotask (node:internal/process/task_queues:137:8)
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)`

2024-04-13 01:11 UTC, iporollo requested changes

2024-04-13 01:11 UTC, iporollo commented on components/EventsColumn.tsx
> +  }
types and interface definitions should be outside of components

2024-04-13 01:11 UTC, iporollo commented on components/EventsColumn.tsx
> +      console.error('no search input');
console.error not necessary here

2024-04-14 19:22 UTC, nj606214 commented on components/EventsColumn.tsx
> +    });
hmm not seeing that on my end, do you have the latest updates from feat/event_search_endpoint on platform-api running? heres a link to that pr https://github.com/cerebralvalley/platform-api/pull/51

2024-06-02 15:31 UTC, closed without merging