Feat/date range in search
iporollo/cerebralvalley-events pull request #4
Opened 2024-04-19 17:21 UTC by nj606214

think we're working here boys.

2024-04-21 22:03 UTC, raydelvecchio commented on pages/api/events/search.ts
> +        });
This API call receives the following error: 
<img width="628" alt="IMG_3879" src="https://github.com/iporollo/cerebralvalley-events/assets/96444588/a02e5b4f-fdf1-4d77-97b0-5581f4324a94">

definitely a backend thing to fix since it crashes the prod instance of platform api

2024-04-21 22:05 UTC, raydelvecchio commented on pages/api/events/search.ts
> +        if (!response.ok) {
<img width="582" alt="image" src="https://github.com/iporollo/cerebralvalley-events/assets/96444588/cbe26ec7-a723-4db5-90d0-1df201a8ca60">
Receiving the following error of JSON parsing on the results too as soon as I press enter to search a term

2024-04-21 22:05 UTC, raydelvecchio reviewed
great placement of the search bar i actually like that a ton

2024-04-21 22:40 UTC, iporollo commented on components/DatePickerWithRange.tsx
> +            disabled
why are we disabling this?

2024-04-22 22:23 UTC, iporollo requested changes
Requesting a few changes which were discussed on call

1. Restyle searchbar
2. Move searchbar above submit button
3. Bring back featured events
4. No re-querying when user erases search query, only do it when user hits the X in the search bar

2024-04-26 00:11 UTC, iporollo reviewed
<img width="496" alt="image" src="https://github.com/iporollo/cerebralvalley-events/assets/14094284/91049b03-48d8-4e0e-946f-5ffe33482387">
<img width="699" alt="image" src="https://github.com/iporollo/cerebralvalley-events/assets/14094284/e913e650-8d6d-4b01-b7ff-eb82abfcc94a">


Few things here in mobile view
1. lets put the search above the filters
2. lets remove the google sheets link in mobile view
3. the submit button seems to have improper styling on certain screen widths

2024-04-26 00:16 UTC, iporollo requested changes
Could we make the design of the search bar similar to how shadcn does their docs search https://ui.shadcn.com/docs/components/accordion

<img width="1512" alt="Screenshot 2024-04-25 at 5 13 55 PM" src="https://github.com/iporollo/cerebralvalley-events/assets/14094284/c53cff79-8510-442d-81d0-e1ec0679a604">

This would be just the searchbar, adding the whole pop out can be a later task

But for our design instead of the command K it should should be a right pointing arrow, and when clicked / pressed enter it becomes an x

2024-06-04 21:55 UTC, iporollo approved these changes
LGTM!

2024-06-04 21:55 UTC, merged